image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\gopath\src\github.com\skycoin\hardware-wallet-daemon

environment:
  GOPATH: c:\gopath
  GOX_OUTPUT: .gox_output

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/gz-c/gox

build_script:
  - cd build
  - cmd: bash ./build.sh 'windows/amd64 windows/386'
  - ps: ls release\
  - ps: cd ..

after_build:
  - ps: 7z a skyd.zip C:\gopath\src\github.com\skycoin\hardware-wallet-daemon\build\release\*
  - ps: ls *.zip

test: off

artifacts:
  - path: skyd.zip
    name: published

deploy:
  release: skyd-$(appveyor_build_version)
  description: 'skycoin hardware wallet daemon'
  provider: GitHub
  auth_token:
    secure: XhcygsUScJdV+tW0+JS7FyRBdHm0Bf0j3ejFpzrO12tNFt3V5TBryZPrCeDQkhaA/7D2vBbjeBqH6PqBIlx59TUF8ulgPUzvUhemAeafKGVeVp72tc2gukDZ6nk3pkOSRPg48653EDZy7tcXLWJ0c1u/64IqPYqeCfv7P+xtTT3EXtpClV/hMAYGSCEnAk3nghYjavmMYA5wYCFpMsAHOqoq03OpMIVeUHR7MgbgqWfgEMLKnlaTNWL3B4XeH6xpI44KXx0MPyBxk3Tl3q1BAIZYQmhXKRh81y58bCPzqX9rS0EZ+zpXBOJbQ8bFGTyZZVZQ/BE2QqE/vxgQDDfLhJp8V+mOekcjp/OTB2J6gVvI6ne2YDs2hoeELoN3pbRtWVD9Q1EPHOI2NpEiORhI+ycSjTKLipt5tzw/+uw4KOZre30mrNqlbwznck/SNyFcKAGLD169cS6d/D4BVWV94dYE4ux+5e0fEDl/EKFVF/uWlbufGpoI9WdQq+WEYDW8bvsREehZs3QiSvKCyBhLDWqI4JV2BMjakqWKKwNSOB3RNdMRP6kB50QrI92H8cvFLrO2llTXNmJRFnoJMxpqxlCjMD6BtQXmz08yQfhBM1bd820VJ7Ns5nIlAplEbLYmpCxTJRrtLFstKFmRVJTQoVY3Pc3WTaW24gjrf85el3o=
  artifact: published            # upload all NuGet packages to release assets
  draft: true
  prerelease: true
  on:
    branch: 40-release

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
