sudo: required
language: go
go:
  - "1.11.x"
services:
  - xvfb

matrix:
  include:
    - os: linux
      env:
        - PIP='sudo pip'
env:
  global:
    - XARGS="-screen 0 1024x768x24"
install:
  - make install-linters
  # Install OS-specific test and build dependencies
  - sh "ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  # Define env vars for osx builds
  # Include paths for brew packages e.g. SDL2
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2" ;
    fi
before_script:
  # Start Xvfb on osx
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    ( sudo Xvfb :99 -ac ${XARGS}; echo "Xvfb ok" )&
    fi
  # Install hardware wallet for running tests against emulator
  - mkdir -p tmp/hardware-wallet
  - git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git tmp/hardware-wallet
  - git -C tmp/hardware-wallet checkout develop
  - git -C tmp/hardware-wallet submodule init
  - git -C tmp/hardware-wallet submodule update
  - git -C tmp/hardware-wallet submodule update --remote
  # Install OS-specific test and build dependencies for hardware-wallet
  - ( cd ./tmp/hardware-wallet && sh "ci-scripts/install-${TRAVIS_OS_NAME}.sh" )
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    ls -l /usr/local/bin/protoc;
    export PATH="/usr/local/bin:$(pwd)/tmp/hardware-wallet/protoc/bin:$PATH";
    fi
  # Include paths for brew packages e.g. SDL2
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2" ;
    fi
  - echo "PATH=$PATH";
  - echo "PIP=$PIP";
script:
  - make -C tmp/hardware-wallet clean
  - make -C tmp/hardware-wallet/tiny-firmware/protob install-deps-nanopb
  - make -C tmp/hardware-wallet/tiny-firmware/protob install-protoc
  - make -C tmp/hardware-wallet/tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
  - make -C tmp/hardware-wallet emulator
  # On GNU/Linux wrap emulator in xvfb graphics context
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    xvfb-run --server-args="${XARGS}" make -C ./tmp/hardware-wallet run-emulator & true ;
    fi
  # On osx Xvfb started in before_script step
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    make -C ./tmp/hardware-wallet run-emulator & true ;
    fi
  # Run self-tests
  - make lint
  - ps aux | grep emulator
  - make test
  - make integration-test-emulator
  - make integration-test-emulator-enable-csrf
  - ./ci-scripts/build-daemon.sh;
after_script:
  - kill -s KILL $(pgrep emulator)

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: releases
  api_key:
    secure: XhcygsUScJdV+tW0+JS7FyRBdHm0Bf0j3ejFpzrO12tNFt3V5TBryZPrCeDQkhaA/7D2vBbjeBqH6PqBIlx59TUF8ulgPUzvUhemAeafKGVeVp72tc2gukDZ6nk3pkOSRPg48653EDZy7tcXLWJ0c1u/64IqPYqeCfv7P+xtTT3EXtpClV/hMAYGSCEnAk3nghYjavmMYA5wYCFpMsAHOqoq03OpMIVeUHR7MgbgqWfgEMLKnlaTNWL3B4XeH6xpI44KXx0MPyBxk3Tl3q1BAIZYQmhXKRh81y58bCPzqX9rS0EZ+zpXBOJbQ8bFGTyZZVZQ/BE2QqE/vxgQDDfLhJp8V+mOekcjp/OTB2J6gVvI6ne2YDs2hoeELoN3pbRtWVD9Q1EPHOI2NpEiORhI+ycSjTKLipt5tzw/+uw4KOZre30mrNqlbwznck/SNyFcKAGLD169cS6d/D4BVWV94dYE4ux+5e0fEDl/EKFVF/uWlbufGpoI9WdQq+WEYDW8bvsREehZs3QiSvKCyBhLDWqI4JV2BMjakqWKKwNSOB3RNdMRP6kB50QrI92H8cvFLrO2llTXNmJRFnoJMxpqxlCjMD6BtQXmz08yQfhBM1bd820VJ7Ns5nIlAplEbLYmpCxTJRrtLFstKFmRVJTQoVY3Pc3WTaW24gjrf85el3o=
  file_glob: true
  file: build/release/*
  draft: true
  on:
    repo: skycoin/hardware-wallet-daemon
    branch: 40-release
