sudo: required
language: go
go:
- 1.11.x

services:
- xvfb
- docker

matrix:
  include:
  - os: linux
    env:
    - PIP='sudo pip'

env:
  global:
  - XARGS="-screen 0 1024x768x24"

install:
- docker pull karalabe/xgo-latest
- go get github.com/karalabe/xgo
- make install-linters
- sh "ci-scripts/install-${TRAVIS_OS_NAME}.sh"
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2"
  ; fi

before_script:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then ( sudo Xvfb :99 -ac ${XARGS}; echo "Xvfb
  ok" )& fi
- mkdir -p tmp/hardware-wallet
- git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git
  tmp/hardware-wallet
- git -C tmp/hardware-wallet checkout develop
- git -C tmp/hardware-wallet submodule init
- git -C tmp/hardware-wallet submodule update
- git -C tmp/hardware-wallet submodule update --remote
- ( cd ./tmp/hardware-wallet && sh "ci-scripts/install-${TRAVIS_OS_NAME}.sh" )
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ls -l /usr/local/bin/protoc; export PATH="/usr/local/bin:$(pwd)/tmp/hardware-wallet/protoc/bin:$PATH";
  fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export SDL_INCLUDE="$(brew --prefix sdl2)/include/SDL2"
  ; fi
- echo "PATH=$PATH";
- echo "PIP=$PIP";

script:
- make -C tmp/hardware-wallet clean
- make -C tmp/hardware-wallet/tiny-firmware/protob install-deps-nanopb
- make -C tmp/hardware-wallet/tiny-firmware/protob install-protoc
- make -C tmp/hardware-wallet/tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
- make -C tmp/hardware-wallet emulator
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then xvfb-run --server-args="${XARGS}"
  make -C ./tmp/hardware-wallet run-emulator & true ; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make -C ./tmp/hardware-wallet run-emulator
  & true ; fi
- make lint
- ps aux | grep emulator
- make test
- make test-integration-emulator
- make test-integration-emulator-enable-csrf

after_script:
- kill -s KILL $(pgrep emulator)

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
- make release

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET
    skip_cleanup: true
    local_dir: build/release
    upload-dir: wallet
    acl: public_read
    region: $AWS_REGION
    on:
      repo: skycoin/hardware-wallet-daemon
      branch: master
