// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/SkycoinProject/hardware-wallet-daemon/src/models"
)

// NewPostBitcoinTransactionSignParams creates a new PostBitcoinTransactionSignParams object
// with the default values initialized.
func NewPostBitcoinTransactionSignParams() *PostBitcoinTransactionSignParams {
	var ()
	return &PostBitcoinTransactionSignParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostBitcoinTransactionSignParamsWithTimeout creates a new PostBitcoinTransactionSignParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostBitcoinTransactionSignParamsWithTimeout(timeout time.Duration) *PostBitcoinTransactionSignParams {
	var ()
	return &PostBitcoinTransactionSignParams{

		timeout: timeout,
	}
}

// NewPostBitcoinTransactionSignParamsWithContext creates a new PostBitcoinTransactionSignParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostBitcoinTransactionSignParamsWithContext(ctx context.Context) *PostBitcoinTransactionSignParams {
	var ()
	return &PostBitcoinTransactionSignParams{

		Context: ctx,
	}
}

// NewPostBitcoinTransactionSignParamsWithHTTPClient creates a new PostBitcoinTransactionSignParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostBitcoinTransactionSignParamsWithHTTPClient(client *http.Client) *PostBitcoinTransactionSignParams {
	var ()
	return &PostBitcoinTransactionSignParams{
		HTTPClient: client,
	}
}

/*PostBitcoinTransactionSignParams contains all the parameters to send to the API endpoint
for the post bitcoin transaction sign operation typically these are written to a http.Request
*/
type PostBitcoinTransactionSignParams struct {

	/*BitcoinTransactionSignRequest
	  BitcoinTransactionSignRequest is request data for /api/v1/bitcoin_transaction_sign

	*/
	BitcoinTransactionSignRequest *models.BitcoinTransactionSignRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) WithTimeout(timeout time.Duration) *PostBitcoinTransactionSignParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) WithContext(ctx context.Context) *PostBitcoinTransactionSignParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) WithHTTPClient(client *http.Client) *PostBitcoinTransactionSignParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBitcoinTransactionSignRequest adds the bitcoinTransactionSignRequest to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) WithBitcoinTransactionSignRequest(bitcoinTransactionSignRequest *models.BitcoinTransactionSignRequest) *PostBitcoinTransactionSignParams {
	o.SetBitcoinTransactionSignRequest(bitcoinTransactionSignRequest)
	return o
}

// SetBitcoinTransactionSignRequest adds the bitcoinTransactionSignRequest to the post bitcoin transaction sign params
func (o *PostBitcoinTransactionSignParams) SetBitcoinTransactionSignRequest(bitcoinTransactionSignRequest *models.BitcoinTransactionSignRequest) {
	o.BitcoinTransactionSignRequest = bitcoinTransactionSignRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostBitcoinTransactionSignParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BitcoinTransactionSignRequest != nil {
		if err := r.SetBodyParam(o.BitcoinTransactionSignRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
