// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SkycoinProject/hardware-wallet-daemon/src/models"
)

// PostBitcoinTransactionSignReader is a Reader for the PostBitcoinTransactionSign structure.
type PostBitcoinTransactionSignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBitcoinTransactionSignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostBitcoinTransactionSignOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostBitcoinTransactionSignDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostBitcoinTransactionSignOK creates a PostBitcoinTransactionSignOK with default headers values
func NewPostBitcoinTransactionSignOK() *PostBitcoinTransactionSignOK {
	return &PostBitcoinTransactionSignOK{}
}

/*PostBitcoinTransactionSignOK handles this case with default header values.

success
*/
type PostBitcoinTransactionSignOK struct {
	Payload *models.HTTPSuccessResponse
}

func (o *PostBitcoinTransactionSignOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostBitcoinTransactionSignDefault creates a PostBitcoinTransactionSignDefault with default headers values
func NewPostBitcoinTransactionSignDefault(code int) *PostBitcoinTransactionSignDefault {
	return &PostBitcoinTransactionSignDefault{
		_statusCode: code,
	}
}

/*PostBitcoinTransactionSignDefault handles this case with default header values.

error
*/
type PostBitcoinTransactionSignDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post bitcoin transaction sign default response
func (o *PostBitcoinTransactionSignDefault) Code() int {
	return o._statusCode
}

func (o *PostBitcoinTransactionSignDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostBitcoinTransactionSignDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
