// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BitcoinTransactionOutput bitcoin transaction output
//
// swagger:model BitcoinTransactionOutput
type BitcoinTransactionOutput struct {

	// address
	// Required: true
	Address *string `json:"address"`

	// address index
	// Required: true
	AddressIndex *int64 `json:"address_index"`

	// coins
	// Required: true
	Coins *string `json:"coins"`
}

// Validate validates this bitcoin transaction output
func (m *BitcoinTransactionOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAddressIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCoins(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BitcoinTransactionOutput) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *BitcoinTransactionOutput) validateAddressIndex(formats strfmt.Registry) error {

	if err := validate.Required("address_index", "body", m.AddressIndex); err != nil {
		return err
	}

	return nil
}

func (m *BitcoinTransactionOutput) validateCoins(formats strfmt.Registry) error {

	if err := validate.Required("coins", "body", m.Coins); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BitcoinTransactionOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BitcoinTransactionOutput) UnmarshalBinary(b []byte) error {
	var res BitcoinTransactionOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
