// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BitcoinTransactionSignRequest bitcoin transaction sign request
//
// swagger:model BitcoinTransactionSignRequest
type BitcoinTransactionSignRequest struct {

	// bitcoin transaction inputs
	// Required: true
	BitcoinTransactionInputs []*BitcoinTransactionInput `json:"bitcoin_transaction_inputs"`

	// bitcoin transaction outputs
	// Required: true
	BitcoinTransactionOutputs []*BitcoinTransactionOutput `json:"bitcoin_transaction_outputs"`
}

// Validate validates this bitcoin transaction sign request
func (m *BitcoinTransactionSignRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBitcoinTransactionInputs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBitcoinTransactionOutputs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BitcoinTransactionSignRequest) validateBitcoinTransactionInputs(formats strfmt.Registry) error {

	if err := validate.Required("bitcoin_transaction_inputs", "body", m.BitcoinTransactionInputs); err != nil {
		return err
	}

	for i := 0; i < len(m.BitcoinTransactionInputs); i++ {
		if swag.IsZero(m.BitcoinTransactionInputs[i]) { // not required
			continue
		}

		if m.BitcoinTransactionInputs[i] != nil {
			if err := m.BitcoinTransactionInputs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("bitcoin_transaction_inputs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BitcoinTransactionSignRequest) validateBitcoinTransactionOutputs(formats strfmt.Registry) error {

	if err := validate.Required("bitcoin_transaction_outputs", "body", m.BitcoinTransactionOutputs); err != nil {
		return err
	}

	for i := 0; i < len(m.BitcoinTransactionOutputs); i++ {
		if swag.IsZero(m.BitcoinTransactionOutputs[i]) { // not required
			continue
		}

		if m.BitcoinTransactionOutputs[i] != nil {
			if err := m.BitcoinTransactionOutputs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("bitcoin_transaction_outputs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BitcoinTransactionSignRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BitcoinTransactionSignRequest) UnmarshalBinary(b []byte) error {
	var res BitcoinTransactionSignRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
